### ISSUE TITLE
Update to 1.18.X

### ISSUE THREAD

**Issue by Lord-Memester** [abigailfails/HelpfulHitboxes-Fabric#1]
Please update to 1.18.X! Super useful!

(If you can't update it, please explain why. It'll likely stop me from pestering you.)

**Comment by JustinNitoi** [comment]
This is how I changed it:

Install the 1.16 version, then extract the .jar file, modify the "fabric.mod.json" and change the version from "1.16.x" to "1.18.x". After zip all the files that you have extracted, and rename the file format from ".zip" to ".jar". Then the mod should work on 1.18.

**Comment by Lord-Memester** [comment]
well, yes, but that leaves a lot to be desired. I've done that regularly myself.

**Comment by solarsonata** [comment]
I'm back in modding finally, it's [been updated](https://www.curseforge.com/minecraft/mc-mods/helpful-hitboxes/files) to 1.19. I won't be able to maintain multiple versions at once, so I'm sorry if you're still using 1.18 :(
